version: '3'
services:
  grakn:
    image: graknlabs/grakn:1.5.7
    ports:
      - 48555:48555 
    volumes:
      - grakndata:/grakn-core-all-linux/server/db
    restart: always
  redis:
    image: redis:5.0.5
    restart: always
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
  rabbitmq:
    image: rabbitmq:3.7.17-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest    
    restart: always
  opencti:
    image: opencti/platform:1.1.1
    environment:
      - APP__PORT=8080
      - APP__ADMIN__EMAIL=admin@opencti.io
      - APP__ADMIN__PASSWORD=ChangeMe
      - APP__ADMIN__TOKEN=ChangeMe
      - APP__LOGS=./logs
      - APP__REACTIVE=true
      - APP__COOKIE_SECURE=false
      - GRAKN__HOSTNAME=grakn
      - GRAKN__PORT=48555
      - GRAKN__TIMEOUT=30000
      - REDIS__HOSTNAME=redis
      - REDIS__PORT=6379
      - ELASTICSEARCH__URL=http://elasticsearch:9200
      - RABBITMQ__HOSTNAME=rabbitmq
      - RABBITMQ__PORT=5672
      - RABBITMQ__PORT_MANAGEMENT=15672
      - RABBITMQ__MANAGEMENT_SSL=false
      - RABBITMQ__USERNAME=guest
      - RABBITMQ__PASSWORD=guest
    ports:
      - "8080:8080"
    depends_on:
      - grakn
      - redis
      - elasticsearch
      - rabbitmq
    restart: always
  worker-import:
    image: opencti/worker:1.1.1
    environment:
      - WORKER_TYPE=import
      - WORKER_LOG_LEVEL=info
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=ChangeMe
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_PORT_MANAGEMENT=15672
      - RABBITMQ_MANAGEMENT_SSL=false
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    depends_on:
      - opencti
    deploy:
      mode: replicated
      replicas: 4
    restart: always
  worker-export:
    image: opencti/worker:1.1.1
    environment:
      - WORKER_TYPE=export
      - WORKER_LOG_LEVEL=info
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=ChangeMe
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_PORT_MANAGEMENT=15672
      - RABBITMQ_MANAGEMENT_SSL=false
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    depends_on:
      - opencti
    deploy:
      mode: replicated
      replicas: 2      
    restart: always
  connector-opencti:
    image: opencti/connector-opencti:1.1.1
    environment:
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_PORT=5672 
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - OPENCTI_NAME=OpenCTI
      - OPENCTI_CONFIDENCE_LEVEL=5
      - OPENCTI_SECTORS_FILE_URL=https://raw.githubusercontent.com/OpenCTI-Platform/datasets/master/data/sectors.json
      - OPENCTI_ENTITIES=identity,sector,region,country,city
      - OPENCTI_INTERVAL=1 # Days
      - OPENCTI_LOG_LEVEL=info
    depends_on:
      - opencti
    restart: always
  connector-mitre:
    image: opencti/connector-mitre:1.1.1
    environment:
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_PORT=5672 
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - MITRE_NAME=MITRE\ ATT&CK
      - MITRE_CONFIDENCE_LEVEL=3
      - MITRE_ENTERPRISE_FILE_URL=https://raw.githubusercontent.com/mitre/cti/master/enterprise-attack/enterprise-attack.json
      - MITRE_ENTITIES=identity,attack-pattern,course-of-action,intrusion-set,malware,tool
      - MITRE_INTERVAL=7 # Days
      - MITRE_LOG_LEVEL=info    
    depends_on:
      - opencti
    restart: always            
volumes:
  grakndata:
  esdata:
