version: '3'
services:
  grakn:
    image: graknlabs/grakn:1.5.7
    ports:
      - 48555:48555 
    volumes:
      - grakndata:/grakn-core-all-linux/server/db
    restart: always
  redis:
    image: redis:5.0.5
    restart: always
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
  rabbitmq:
    image: rabbitmq:3.7.16-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest    
    restart: always
  worker:
    image: opencti/worker:1.1.0
    environment:
      - OPENCTI_HOSTNAME=opencti
      - OPENCTI_PORT=8080
      - OPENCTI_TOKEN=ChangeMe
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    depends_on:
      - opencti
    restart: always
  integration:
    image: opencti/integration:1.1.0
    environment:
      - OPENCTI_HOSTNAME=opencti
      - OPENCTI_PORT=8080
      - OPENCTI_TOKEN=43aff6bd-fe7a-4547-ba51-77eaed15ba10
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    depends_on:
      - opencti
    restart: always    
  opencti:
    image: opencti/platform:1.1.0
    environment:
      - APP__PORT=8080
      - APP__ADMIN__EMAIL=admin@opencti.io
      - APP__ADMIN__PASSWORD=admin
      - APP__ADMIN__TOKEN=43aff6bd-fe7a-4547-ba51-77eaed15ba10
      - APP__LOGS=./logs
      - APP__CONNECTORS=./integration/connectors
      - APP__REACTIVE=true
      - APP__COOKIE_SECURE=false
      - GRAKN__HOSTNAME=grakn
      - GRAKN__PORT=48555
      - GRAKN__TIMEOUT=30000
      - REDIS__HOSTNAME=redis
      - REDIS__PORT=6379
      - ELASTICSEARCH__HOSTNAME=elasticsearch
      - ELASTICSEARCH__PORT=9200
      - RABBITMQ__HOSTNAME=rabbitmq
      - RABBITMQ__PORT=5672
      - RABBITMQ__PORT_MANAGEMENT=15672
      - RABBITMQ__MANAGEMENT_SSL=false
      - RABBITMQ__USERNAME=guest
      - RABBITMQ__PASSWORD=guest
    ports:
      - "8080:8080"
    depends_on:
      - grakn
      - redis
      - elasticsearch
      - rabbitmq
    restart: always

volumes:
  grakndata:
  esdata:
