version: '3'
services:
  grakn:
    image: graknlabs/grakn:1.5.6
    ports:
      - 48555:48555 
    volumes:
      - grakndata:/grakn-core-all-linux/server/db
    restart: always
  redis:
    image: redis
    restart: always
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    restart: always
  rabbitmq:
    image: rabbitmq:management
    restart: always
  worker:
    image: opencti/worker
    environment:
      - OPENCTI_HOSTNAME=opencti
      - OPENCTI_PORT=8080
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    volumes:
      - config:/opt/opencti/shared_config:rw
    depends_on:
      - opencti
    restart: always
  integration:
    image: opencti/integration
    environment:
      - OPENCTI_HOSTNAME=opencti
      - OPENCTI_PORT=8080
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest      
    volumes:
      - config:/opt/opencti/shared_config:rw
    depends_on:
      - opencti
    restart: always    
  opencti:
    image: opencti/platform
    environment:
      - APP__PORT=8080
      - APP__LOGS=./logs
      - APP__CONNECTORS=./integration/connectors
      - APP__SECRET=ChangeMe
      - APP__REACTIVE=true
      - APP__COOKIE_SECURE=false
      - GRAKN__HOSTNAME=grakn
      - GRAKN__PORT=48555
      - GRAKN__TIMEOUT=30000
      - REDIS__HOSTNAME=redis
      - REDIS__PORT=6379
      - ELASTICSEARCH__HOSTNAME=elasticsearch
      - ELASTICSEARCH__PORT=9200
      - RABBITMQ__HOSTNAME=rabbitmq
      - RABBITMQ__PORT=5672
      - RABBITMQ__PORT_MANAGEMENT=15672
      - RABBITMQ__MANAGEMENT_SSL=false
      - RABBITMQ__USERNAME=guest
      - RABBITMQ__PASSWORD=guest
    ports:
      - "8080:8080"
    volumes:
      - config:/opt/opencti/shared_config:rw
    depends_on:
      - grakn
      - redis
      - elasticsearch
      - rabbitmq
    restart: always

volumes:
  grakndata:
  esdata:
  config:
