site_name: OpenCTI Documentation
site_description: Documentation about OpenCTI, the next-generation Cyber Threat Intelligence platform.
site_author: Filigran
site_url: https://docs.opencti.io
copyright: Â© 2023 Filigran. All rights reserved
repo_name: GitHub
repo_url: https://github.com/OpenCTI-Platform/opencti
edit_uri: https://github.com/OpenCTI-Platform/docs/blob/main/docs/

# Theming
theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  features:
    - navigation.tabs
    - navigation.path
    - navigation.footer
    - navigation.expand
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - search.highlight
  palette:
    scheme: filigran
  font:
    text: IBM Plex Sans
    code: Roboto Mono
# CSS
extra_css:
  - assets/css/custom.css

# Extra
extra:
  version:
    provider: mike
  analytics:
    provider: google
    property: G-DB4K9LZPDZ
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/OpenCTI-Platform
    - icon: fontawesome/brands/medium
      link: https://blog.filigran.io
    - icon: fontawesome/brands/slack
      link: https://community.filigran.io
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/filigran
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/FiligranHQ
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/FiligranHQ

# Plugins
plugins:
  - search
  - git-committers:
      repository: OpenCTI-Platform/docs
      branch: main  
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - glightbox

# Extensions
markdown_extensions: 
  - attr_list
  - md_in_html
  - tables
  - admonition   
  - def_list
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.smartsymbols
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true   
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: false
      auto_title: false
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg   
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets:
      url_download: true

# Page tree
nav:
  - Home: 'index.md'
  - Deployment & Setup:
    - Platform:
      - Overview: deployment/overview.md
      - Installation: deployment/installation.md
      - Configuration: deployment/configuration.md
      - Authentication: deployment/authentication.md
      - Upgrade: deployment/upgrade.md
    - Ecosystem:
      - Connectors: deployment/connectors.md
      - Integrations: deployment/integrations.md
      - Other resources: deployment/resources.md
    - Advanced:
      - Clustering: deployment/clustering.md
      - Indices and rollover: deployment/rollover.md
      - Troubleshooting: deployment/troubleshooting.md
  - User Guide:
    - Introduction: usage/introduction.md
    - Foundations:
      - Data model: usage/data-model.md
      - Nested objects: usage/nested.md
      - Containers: usage/containers.md
      - Deduplication: usage/deduplication.md
    - Explore knowledge:
      - Overview: usage/overview.md
      - Search for knowledge: usage/searching.md
      - Explore by entity types: usage/exploring.md
      - Pivot and investigate: usage/pivoting.md
    - Create knowledge:
      - Automated import: usage/import-automated.md
      - Import from files: usage/import-files.md
      - Manual creations: usage/manual-creation.md
      - Analyst workbench: usage/workbench.md
    - Manipulate knowledge:
      - Enrichment: usage/enrichment.md
      - Inferences and reasoning: usage/inferences.md
      - Notifications and alerting: usage/notifications.md
      - Custom dashboards: usage/dashboards.md
      - Workflows and assignation: usage/workflows.md
    - Sharing and exports:
      - Export in structured format: usage/export-structured.md
      - Export in documents: usage/export-documents.md
      - Native feeds: usage/feeds.md
  - Administration:
    - Introduction: administration/introduction.md
    - Data management:
      - Custom taxonomies: administration/ontologies.md
      - Retention policies: administration/retention.md
      - Merging and de-duplication: administration/merging.md    
    - Settings:
      - Parameters: administration/parameters.md
      - Reasoning engine: administration/reasoning.md
      - Indicators lifecycle: administration/indicators.md
      - Customize entities: administration/entities.md
    - Security and traceability:
      - Users and RBAC: administration/users.md
      - Data segregation: administration/segregation.md
      - Sourcing knowledge: administration/sourcing.md
      - Audit and monitoring: administration/audit.md
  - Reference:
    - Data:
      - Data model: reference/data-model.md
      - Taxonomy: reference/taxonomy.md
      - Knowledge graph: reference/graph.md
    - APIs and feeds:
      - GraphQL API: reference/api.md
      - Events streaming: reference/streaming.md
      - TAXII and CSV: reference/taxii.md
    - Security: reference/security.md
  - Development:
    - APIs and libraries:
      - Use the GraphQL API: development/api-usage.md
      - Python library: development/python.md
    - Contributing:
      - Environment setup: development/environment.md
      - Develop a connector: development/connectors.md
