name: Run OpenCTI frontend tests

on:
  workflow_call:
    inputs:
      checkout_ref:
        description: "Reference of the branch or commit sha"
        type: string
        default: ${{ github.sha }}

jobs:
  opencti-frontend-test:
    name: Frontend tests
    runs-on: ubuntu-latest
    steps:
    - name: Simulate front test
      continue-on-error: true
      run: echo "Simulate front test"

  opencti-frontend-e2e-test:
    name: Frontend e2e tests
    runs-on: ubuntu-latest
    steps:
    - name: Simulate e2e test
      continue-on-error: true
      run: echo "Simulate e2e test"

  opencti-frontend-verify-translation:
    name: Verify translation
    runs-on: ubuntu-latest
    steps:
    - name: Simulate verify translation test
      continue-on-error: true
      run: echo "Simulate verify translation test"