name: Run OpenCTI frontend tests

on:
  workflow_call:

jobs:
  opencti-frontend-test:
    runs-on: ubuntu-latest
    steps:
    - name: OpenCTI checkout
      uses: actions/checkout@v4

    - name: Runner information
      continue-on-error: true
      run: ./opencti-platform/opencti-ci/runner-info.sh # Display runner info and start resource monitoring in background

    - name: Frontend tests
      run: |
        docker run  \
          --name frontend-tests \
          -v ${{ github.workspace }}:/home/workspace \
          node:22-alpine \
          sh -c 'set -x
            echo "$(ls /root/.yarn/berry/cache/ 2> /dev/null | wc -l || echo 0) packages in Yarn global cache"
            apk add git tini gcc g++ make musl-dev cargo python3 python3-dev postfix postfix-pcre
            npm install -g node-gyp
            npm install -g corepack
            cd /home/workspace/opencti-platform/opencti-front
            cp /home/workspace/s/opencti-platform/.yarnrc.yml .
            yarn install
            yarn build
            yarn check-ts
            yarn lint
            NODE_OPTIONS=--max_old_space_size=8192 yarn test:coverage
            '

    - name: Print resources stats
      if: always()
      continue-on-error: true
      run: cat runner_resource_stat.log


  opencti-frontend-e2e-test:
    runs-on: ubuntu-latest
    steps:
    - name: OpenCTI checkout
      uses: actions/checkout@v4
      with:
        path: origin

    - name: Runner information
      continue-on-error: true
      run: .origin/opencti-platform/opencti-ci/runner-info.sh # Display runner info and start resource monitoring in background

    - name: Duplicate workspace
      run: cp -pr ${{ github.workspace }}/origin ${{ github.workspace }}/frontend-e2e-test

    - name: Set up Docker Compose for backends
      run: |
         set -ex
         cd origin/opencti-platform/opencti-ci         
         export TAG=${{ needs.build-opencti-platform.outputs.version }}
         docker network create runner-docker-network
         docker compose --profile "backend" up -d

    - name: Start e2e opencti and worker instance
      run: |
        set -x;
        sleep 2;
        echo ${{ github.workspace }};
        ls ${{ github.workspace }};
        ls ${{ github.workspace }}/origin;
        docker run -d --network runner-docker-network \
          --name opencti-e2e-start \
          -p 4500:4100 \
          -v ${{ github.workspace }}/origin:/home/workspace \
          --env-file ${{ github.workspace }}/opencti-platform/opencti-ci/ci-common.env \
          -e APP__ENTERPRISE_EDITION_LICENSE="${{ secrets.EE_LICENSE }}" \
          -e APP__ENABLED_DEV_FEATURES='["*"]' \
          -e APP__CHILD_LOCKING_PROCESS__ENABLED=true \
          -e APP__APP_LOG__EXTENDED_ERROR_MESSAGE=true \
          -e REDIS__NAMESPACE=e2e-start \
          -e ELASTICSEARCH__INDEX_PREFIX=e2e-start \
          -e MINIO__BUCKET_NAME=e2e-start-bucket \
          -e RABBITMQ__QUEUE_PREFIX=e2e-start \
          -e PUBLISHER_MANAGER__ENABLED=false \
          nikolaik/python-nodejs:python3.11-nodejs22-alpine \
          sh -c 'set -ex;        
            echo "$(ls /root/.yarn/berry/cache/ 2> /dev/null | wc -l || echo 0) packages in Yarn global cache"
            apk add build-base git libffi-dev cargo
            mkdir -p /tmp/e2e-start-platform/
            cp -a /home/workspace/* /tmp/e2e-start-platform/
            ls -larth /tmp/e2e-start-platform/
            cd /tmp/e2e-start-platform/client-python
            pip install -r requirements.txt
            pip install -e .[dev,doc]
            cd /tmp/e2e-start-platform/opencti-platform/opencti-graphql
            npm install -g corepack
            cp /tmp/e2e-start-platform/opencti-platform/.yarnrc.yml .
            yarn install
            yarn install:python
            yarn build:dev
            yarn wait-api && node build/script-insert-dataset.js --datasets=DATA-TEST-STIX2_v2,data-test-stix-e2e,poisonivy &
            NODE_OPTIONS=--max_old_space_size=8192 yarn start
            ';
        
        docker run -d --network runner-docker-network \
          --name opencti-e2e-worker \
          -v ${{ github.workspace }}/origin:/home/workspace \
          -e OPENCTI_URL=http://opencti-e2e-start:4100 \
          -e OPENCTI_TOKEN=bfa014e0-e02e-4aa6-a42b-603b19dcf159 \
          -e WORKER_LOG_LEVEL=info \
          nikolaik/python-nodejs:python3.11-nodejs22-alpine \
          sh -c 'set -x;
            sleep 10
            mkdir -p /tmp/opencti-e2e-worker
            cp -a /home/workspace/* /tmp/opencti-e2e-worker
            apk add build-base git libffi-dev cargo
            cd /tmp/opencti-e2e-worker/client-python
            echo "[INFO] using client-python on branch $(git branch --show-current)"
            pip install -r requirements.txt
            pip install -e .[dev,doc]
            while ! nc -z opencti-e2e-start 4100 ; do sleep 1 ; done
            cd /tmp/opencti-e2e-worker/opencti-worker
            pip install -r src/requirements.txt
            python3 src/worker.py
        '

    - name: Wait for OpenCTI sync instances to start
      continue-on-error: true
      run: .${{ github.workspace }}/origin/opencti-platform/opencti-ci/wait-for-opencsti-instance-startup.sh http://localhost:4500/health?health_access_key=cihealthkey 300 10

    - name: Frontend e2e tests
      run: |
        docker run --network runner-docker-network \
          --name frontend-e2e-tests \
          -v ${{ github.workspace }}/frontend-e2e-test:/home/workspace \
          -e BACK_END_URL=http://opencti-e2e-start:4100 \
          -e E2E_TEST=true \
          -e TEAMS_WEBHOOK="teams-webhook-url" \
          node:22.21.0 \
          sh -c 'set -ex;
              echo "$(ls /root/.yarn/berry/cache/ 2> /dev/null | wc -l || echo 0) packages in Yarn global cache"
              apt-get update
              apt-get -y install netcat-traditional
              cd /home/workspace/opencti-platform/opencti-front
              npm install -g corepack
              cp /home/workspace/opencti-platform/.yarnrc.yml .
              yarn install
              npx playwright install --with-deps chromium
              yarn build
              yarn test:e2e
            '

    - name: upload front e2e artifact
      uses: actions/upload-artifact@v4
      if: always()
      continue-on-error: true
      with:
        name: frontend-test-results
        path: ${{ github.workspace }}/frontend-e2e-test/opencti-platform/opencti-front/test-results
        retention-days: 15


    - name: Logs opencti-e2e-start
      if: always()
      continue-on-error: true
      run: docker logs opencti-e2e-start

    - name: Logs opencti-e2e-worker
      if: always()
      continue-on-error: true
      run: docker logs opencti-e2e-worker

    # Output all logs used during the job
    - name: Log backends (Minio, Elastic, RabbitMQ, Redis)
      continue-on-error: true
      run: |
          echo -e "\n\n *********\n ********* logs Minio \n"; docker logs minio
          echo -e "\n\n *********\n ********* logs Elastic search \n"; sleep 1; docker logs elasticsearch
          echo -e "\n\n *********\n ********* logs RabbitMQ \n"; sleep 1; docker logs rabbitmq
          echo -e "\n\n *********\n ********* logs Redis \n"; sleep 1; docker logs redis

    - name: Print resources stats
      if: always()
      continue-on-error: true
      run: cat runner_resource_stat.log
